---
- hosts: DEV_APP
  remote_user: clouduser

  roles:
    - prepare-host-server
    - install-docker-server
    - git-checkout
    - {role: run-mvnw, MVNW_OPTIONS: "-Pdev"}


  tasks:
    - include: tasks/prepare-app-install.yml
      vars:
        app_profiles: common,oracle-dev
    - include: tasks/install-app.yml
      vars:
        container_list: [
          {
            name: romaneio-api-1,
            ports: "8080:8080/tcp"
          }
        ]
