---
  - name: Delete Java installation dir if exists
    file: path="{{java_home}}" state=absent
    become: yes

  - name: Delete java installation file if exists
    file: path="{{java_installation_file_path}}" state=absent
    become: yes

  - name: Downdload Java
    command: "wget -O {{java_installation_file_path}} --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie;' {{java_download_url}}"
    become: yes
    environment:
      http_proxy: "{{http_proxy}}"
      https_proxy: "{{https_proxy}}"

  - name: Desempacota tar
    unarchive: src={{java_installation_file_path}} dest={{java_installation_dir}} copy=no
    become: yes

  - name: Set JAVA_HOME env
    lineinfile: dest=/etc/environment regexp="^JAVA_HOME=" line="JAVA_HOME=\"{{java_home}}\""
    become: yes
  - name: Add Java to PATH env
    lineinfile: dest="/home/clouduser/.profile" regexp=^PATH=.*$JAVA_HOME line="PATH=\"${JAVA_HOME}/bin:${PATH}\""
    become: yes

  - name: Delete java installation file if exists
    file: path="{{java_installation_file_path}}" state=absent
    become: yes