---

  - name: Delete app dir if exists
    file: path={{app_install_dir}} state=absent

  - name: Create app dir
    become: yes
    file: path="{{app_install_dir}}/{{app_name}}" state=directory mode="u+rwx,g+rwx,o+rwx"

  - name: Upload app
    copy: src="{{item}}" dest="{{app_install_dir}}"
    with_items:
      - "temp/{{app_name}}"
      - "temp/Dockerfile"


  - name: Setting run script perms
    file: path="{{app_install_dir}}/{{app_name}}/run.sh" mode="u+rwx,g-w,g+x,o-rwx"

  - debug: "{{app_install_dir}}/{{app_name}}"


  - name: "Remove existent image"
    docker_image:
      state: absent
      force: yes
      name: log-api-romaneio
      tag: v1

  - name: Build DockerImage
    become: yes
    environment: "{{proxy_env}}"
    docker_image:
      name: log-api-romaneio
      state: present
      force: yes
      tag: v1
      path: "{{app_install_dir}}"

#  - name: "Test"
#    debug: msg="Valor é {{item}}"
#    with_items: "{{container_list}}"
    
  - name: Start containers
    docker_container:
      name: "{{item.name}}"
      hostname: "{{item.name}}"
      image: log-api-romaneio:v1
      state: started
      restart: yes
      ports: "{{item.ports}}"
      command: /apps/apis/romaneio/run.sh
    with_items: "{{container_list}}"
