---

  - name: Cleaning
    run_once: true
    local_action: file path="{{item}}" state=absent
    with_items:
      - "temp/{{app_name}}"

  - name: Create temp directories
    run_once: true
    local_action: file path="{{item}}" state=directory
    with_items:
      - "temp/{{app_name}}"

  - name: "Copy files to temp/{{app_name}}"
    run_once: true
    local_action: copy src="{{item}}" dest="temp/{{app_name}}"
    with_items:
      - "{{APP_FILE_PATH}}"
      - resources/run.sh

  - name: Discover app jar name
    run_once: true
    local_action: shell basename $(ls {{APP_FILE_PATH}} | head -1)
    register: app_jar_name

  - name: "Set jar name in run.sh"
    run_once: true
    local_action: replace dest="temp/{{app_name}}/run.sh" regexp="__JAR_NAME__" replace="{{app_jar_name.stdout_lines[0]}}"


  - name: Copy Dockerfile
    run_once: true
    local_action: copy src="resources/Dockerfile" dest="temp/"


